-- Phase 1 (requisición workflow): add the requisición content columns parsed
-- from the .docx into dim_requisitions. Idempotent — safe to re-run.

IF COL_LENGTH('dbo.dim_requisitions','puesto') IS NULL                  ALTER TABLE dbo.dim_requisitions ADD puesto NVARCHAR(300) NULL;
IF COL_LENGTH('dbo.dim_requisitions','direccion') IS NULL               ALTER TABLE dbo.dim_requisitions ADD direccion NVARCHAR(200) NULL;
IF COL_LENGTH('dbo.dim_requisitions','region_area') IS NULL             ALTER TABLE dbo.dim_requisitions ADD region_area NVARCHAR(200) NULL;
IF COL_LENGTH('dbo.dim_requisitions','asesor_rh') IS NULL               ALTER TABLE dbo.dim_requisitions ADD asesor_rh NVARCHAR(200) NULL;
IF COL_LENGTH('dbo.dim_requisitions','manager_email') IS NULL           ALTER TABLE dbo.dim_requisitions ADD manager_email NVARCHAR(200) NULL;
IF COL_LENGTH('dbo.dim_requisitions','carrera_requerida') IS NULL       ALTER TABLE dbo.dim_requisitions ADD carrera_requerida NVARCHAR(200) NULL;
IF COL_LENGTH('dbo.dim_requisitions','semestre_requerido') IS NULL      ALTER TABLE dbo.dim_requisitions ADD semestre_requerido NVARCHAR(50) NULL;
IF COL_LENGTH('dbo.dim_requisitions','disponibilidad_horario') IS NULL  ALTER TABLE dbo.dim_requisitions ADD disponibilidad_horario NVARCHAR(200) NULL;
IF COL_LENGTH('dbo.dim_requisitions','periodo_estadia') IS NULL         ALTER TABLE dbo.dim_requisitions ADD periodo_estadia NVARCHAR(100) NULL;
IF COL_LENGTH('dbo.dim_requisitions','fecha_inicio_solicitada') IS NULL ALTER TABLE dbo.dim_requisitions ADD fecha_inicio_solicitada DATE NULL;
IF COL_LENGTH('dbo.dim_requisitions','fecha_termino_solicitada') IS NULL ALTER TABLE dbo.dim_requisitions ADD fecha_termino_solicitada DATE NULL;
IF COL_LENGTH('dbo.dim_requisitions','descripcion_proyecto') IS NULL    ALTER TABLE dbo.dim_requisitions ADD descripcion_proyecto NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.dim_requisitions','retos') IS NULL                   ALTER TABLE dbo.dim_requisitions ADD retos NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.dim_requisitions','responsabilidades') IS NULL       ALTER TABLE dbo.dim_requisitions ADD responsabilidades NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.dim_requisitions','entregables') IS NULL             ALTER TABLE dbo.dim_requisitions ADD entregables NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.dim_requisitions','habilidades') IS NULL             ALTER TABLE dbo.dim_requisitions ADD habilidades NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.dim_requisitions','modalidad') IS NULL               ALTER TABLE dbo.dim_requisitions ADD modalidad NVARCHAR(50) NULL;
IF COL_LENGTH('dbo.dim_requisitions','prioridad') IS NULL               ALTER TABLE dbo.dim_requisitions ADD prioridad NVARCHAR(50) NULL;
IF COL_LENGTH('dbo.dim_requisitions','convenio_requerido') IS NULL      ALTER TABLE dbo.dim_requisitions ADD convenio_requerido BIT NULL;
IF COL_LENGTH('dbo.dim_requisitions','needs_review') IS NULL            ALTER TABLE dbo.dim_requisitions ADD needs_review BIT NULL;
IF COL_LENGTH('dbo.dim_requisitions','parse_notes') IS NULL             ALTER TABLE dbo.dim_requisitions ADD parse_notes NVARCHAR(MAX) NULL;
IF COL_LENGTH('dbo.dim_requisitions','source_container') IS NULL        ALTER TABLE dbo.dim_requisitions ADD source_container NVARCHAR(200) NULL;
IF COL_LENGTH('dbo.dim_requisitions','source_blob_name') IS NULL        ALTER TABLE dbo.dim_requisitions ADD source_blob_name NVARCHAR(400) NULL;
IF COL_LENGTH('dbo.dim_requisitions','source_file_id') IS NULL          ALTER TABLE dbo.dim_requisitions ADD source_file_id NVARCHAR(50) NULL;
