IF OBJECT_ID('dbo.dim_interns', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.dim_interns (
        intern_id NVARCHAR(50) NOT NULL PRIMARY KEY,
        num_empleado NVARCHAR(50) NULL,
        num_empleado_cemex NVARCHAR(50) NULL,
        nss NVARCHAR(50) NULL,
        rfc NVARCHAR(50) NULL,
        curp NVARCHAR(50) NULL,
        nombre NVARCHAR(150) NULL,
        paterno NVARCHAR(150) NULL,
        materno NVARCHAR(150) NULL,
        nombre_completo NVARCHAR(300) NULL,
        sexo NVARCHAR(50) NULL,
        edad INT NULL,
        universidad NVARCHAR(255) NULL,
        carrera NVARCHAR(255) NULL,
        semestre NVARCHAR(50) NULL,
        puesto NVARCHAR(300) NULL,
        jefe_inmediato NVARCHAR(255) NULL,
        ubicacion_hc NVARCHAR(255) NULL,
        estado_ubicacion_hc NVARCHAR(255) NULL,
        asesor_rrhh_hc NVARCHAR(255) NULL,
        salario_mensual NVARCHAR(100) NULL,
        cc_hc NVARCHAR(255) NULL,
        vp_hc NVARCHAR(255) NULL,
        region_rh NVARCHAR(255) NULL,
        oi_hc NVARCHAR(255) NULL,
        cia_hc NVARCHAR(255) NULL,
        area NVARCHAR(255) NULL,
        status_id NVARCHAR(100) NULL,
        fecha_de_ingreso DATE NULL,
        fecha_contrato_vence DATE NULL,
        email_personal NVARCHAR(200) NULL,
        telefono NVARCHAR(50) NULL,
        estado_civil NVARCHAR(50) NULL,
        nacionalidad NVARCHAR(50) NULL,
        matricula NVARCHAR(50) NULL,
        grado NVARCHAR(100) NULL,
        fecha_nacimiento DATE NULL,
        calle NVARCHAR(200) NULL,
        numero_exterior NVARCHAR(50) NULL,
        colonia NVARCHAR(150) NULL,
        poblacion NVARCHAR(150) NULL,
        estado_direccion NVARCHAR(100) NULL,
        codigo_postal NVARCHAR(20) NULL,
        requisition_id NVARCHAR(50) NULL,
        candidate_source_blob NVARCHAR(400) NULL,
        candidate_needs_review BIT NULL,
        candidate_validation_notes NVARCHAR(MAX) NULL,
        cemex_id NVARCHAR(50) NULL,
        correo_institucional NVARCHAR(200) NULL,
        ubicacion_udn NVARCHAR(150) NULL,
        compania NVARCHAR(150) NULL,
        ubicacion_estado NVARCHAR(100) NULL,
        oi NVARCHAR(50) NULL,
        cc NVARCHAR(50) NULL,
        fecha_graduacion NVARCHAR(50) NULL,
        hr_list_matched BIT NULL,
        apodo NVARCHAR(100) NULL,
        linkedin NVARCHAR(300) NULL,
        contacto_emergencia NVARCHAR(500) NULL,
        documents_status NVARCHAR(40) NULL,
        convenio_status NVARCHAR(40) NULL,
        created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        updated_at DATETIME2 NULL
    );
END;
GO

IF COL_LENGTH('dbo.dim_interns', 'created_at') IS NULL
    ALTER TABLE dbo.dim_interns ADD created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME();
IF COL_LENGTH('dbo.dim_interns', 'updated_at') IS NULL
    ALTER TABLE dbo.dim_interns ADD updated_at DATETIME2 NULL;
GO
